/** Public account identity only: never derive labels from credentials or token claims. */
export interface AccountIdentity {
  id: string
  providerId: string
  name?: string
  email?: string
  providerUserId?: string
  nameSource?: 'auto' | 'custom'
}

export interface VerifiedAccountInfo {
  email?: string
  userId?: string
}

export function accountEmail(value: unknown): string | undefined {
  if (typeof value !== 'string') return undefined
  const email = value.trim()
  return email.length <= 254 && /^[^\s@<>\x00-\x1f\x7f]+@[^\s@<>\x00-\x1f\x7f]+\.[^\s@<>\x00-\x1f\x7f]+$/.test(email)
    ? email : undefined
}

export function accountUserId(value: unknown): string | undefined {
  if (typeof value === 'number' && Number.isSafeInteger(value) && value >= 0) return String(value)
  if (typeof value !== 'string') return undefined
  const id = value.trim()
  return id && id.length <= 128 && !/[\x00-\x1f\x7f]/.test(id) ? id : undefined
}

export function shortAccountId(id: string): string {
  return id.replace(/[^a-zA-Z0-9]/g, '').slice(-8) || id.slice(-8)
}

export function defaultAccountName(account: AccountIdentity, providerName: string): string {
  return accountEmail(account.email)
    || `${providerName} · ${accountUserId(account.providerUserId) || shortAccountId(account.id)}`
}

/** Recognize only labels generated by old versions; arbitrary nicknames stay untouched. */
export function usesAutomaticAccountName(account: AccountIdentity, providerName: string): boolean {
  const name = typeof account.name === 'string' ? account.name.trim() : ''
  if (!name) return true
  if (account.nameSource) return account.nameSource === 'auto'
  const prefixes = [providerName, account.providerId]
  const labels = prefixes.flatMap(prefix => [prefix, ...['Account', 'Accounts', 'User', '账户', '账号', '用户'].map(suffix => `${prefix} ${suffix}`)])
  return labels.some(label => label.toLowerCase() === name.toLowerCase())
}

export function normalizeAccountIdentity<T extends AccountIdentity>(account: T, providerName: string): T {
  const auto = usesAutomaticAccountName(account, providerName)
  const identity = {
    ...account,
    email: accountEmail(account.email),
    providerUserId: accountUserId(account.providerUserId),
    nameSource: auto ? 'auto' as const : 'custom' as const,
  }
  return { ...identity, name: auto ? defaultAccountName(identity, providerName) : account.name!.trim() }
}

/** Validation can enrich automatic names, but must not erase an existing identity. */
export function validatedAccountIdentity(info?: VerifiedAccountInfo): Pick<AccountIdentity, 'email' | 'providerUserId'> {
  const email = accountEmail(info?.email)
  const providerUserId = accountUserId(info?.userId)
  return { ...(email ? { email } : {}), ...(providerUserId ? { providerUserId } : {}) }
}
